export function makeData() {
  return [{
    id: 1,
    nombre: "Maquillaje",
    valor: 10000,
    categoria: 1,
    stock: 100,
  },
  {
    id: 2,
    nombre: "Delineador",
    valor: 5000,
    categoria: 1,
    stock: 70,
  },
  {
    id: 3,
    nombre: "Humectante",
    valor: 7000,
    categoria: 2,
    stock: 50,
  },
  {
    id: 4,
    nombre: "Mascara",
    valor: 70000,
    categoria: 2,
    stock: 20,
  },
  {
    id: 5,
    nombre: "Aretes",
    valor: 7000,
    categoria: 3,
    stock: 220,
  },
  {
    id: 6,
    nombre: "Collar",
    valor: 30000,
    categoria: 3,
    stock: 70,
  },
  {
    id: 7,
    nombre: "Cuero",
    valor: 300000,
    categoria: 4,
    stock: 20,
  },
  {
    id: 8,
    nombre: "Tejido",
    valor: 100000,
    categoria: 4,
    stock: 40,
  },
  {
    id: 9,
    nombre: "Pantalon",
    valor: 100000,
    categoria: 5,
    stock: 45,
  },
  {
    id: 10,
    nombre: "Falda",
    valor: 120000,
    categoria: 5,
    stock: 170,
  },
  {
    id: 11,
    nombre: "Tennis",
    valor: 50000,
    categoria: 6,
    stock: 400,
  },
  {
    id: 12,
    nombre: "Zapatos",
    valor: 80000,
    categoria: 6,
    stock: 200,
  },
];
}
